import type { PropsWithChildren } from "react";
import { ScrollViewStyleReset } from "expo-router/html";

import { colors } from "@sidequest/ui/theme";

/**
 * HTML shell for the web build only. Native platforms never render this.
 *
 * The service worker itself is generated by Workbox at build time
 * (`workbox-config.cjs`); this only registers it. Registration is guarded on a
 * secure context because browsers expose `navigator.serviceWorker` solely over
 * HTTPS or on localhost — the same rule that gates the Geolocation API, so on a
 * plain LAN address both are unavailable together.
 */
const serviceWorkerScript = `
  if ('serviceWorker' in navigator && window.isSecureContext) {
    window.addEventListener('load', function () {
      navigator.serviceWorker.register('/sw.js').catch(function (error) {
        console.warn('SideQuest service worker registration failed', error);
      });
    });
  }
`;

/** Painted before the bundle boots, so a cold start does not flash white. */
const backgroundStyle = `
  html, body { background-color: ${colors.canvas}; }
  body { overscroll-behavior-y: none; }
`;

export default function Root({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        {/* viewport-fit=cover so safe-area insets work in standalone mode. */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover, shrink-to-fit=no"
        />
        <meta name="theme-color" content={colors.brandDeep} />
        <meta
          name="description"
          content="Turn real life into a multiplayer adventure with your friends."
        />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="SideQuest" />

        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icons/sidequest.svg" type="image/svg+xml" />
        <link rel="icon" href="/favicon.png" sizes="64x64" type="image/png" />
        {/* iOS ignores both the manifest and SVG icons when adding to the home
            screen, so this PNG is the only thing that gives the installed app a
            real icon instead of a screenshot of the page. */}
        <link rel="apple-touch-icon" href="/icons/icon-180.png" />

        <ScrollViewStyleReset />
        <style dangerouslySetInnerHTML={{ __html: backgroundStyle }} />
        <script dangerouslySetInnerHTML={{ __html: serviceWorkerScript }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
