-- Feature-owned forward-only schema. Final journal registration belongs to integration.
CREATE TABLE quest_templates (id uuid PRIMARY KEY, content jsonb NOT NULL, version integer NOT NULL CHECK (version > 0));
CREATE TABLE quest_instances (id uuid PRIMARY KEY, template_id uuid NOT NULL REFERENCES quest_templates(id), owner_user_id uuid NOT NULL, party_id uuid, participants jsonb NOT NULL, content jsonb NOT NULL, status text NOT NULL CHECK (status IN ('SPAWNED','ACCEPTED','IN_PROGRESS','VERIFIED','FAILED','EXPIRED','DISMISSED')), reward_coins integer NOT NULL CHECK (reward_coins >= 0), source jsonb NOT NULL, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, accepted_at timestamptz, started_at timestamptz, resolved_at timestamptz, version integer NOT NULL CHECK (version > 0));
CREATE INDEX quest_instances_owner_status_idx ON quest_instances(owner_user_id,status,expires_at);
CREATE INDEX quest_instances_party_status_idx ON quest_instances(party_id,status) WHERE party_id IS NOT NULL;
CREATE TABLE quest_verification_attempts (id uuid PRIMARY KEY, quest_id uuid NOT NULL REFERENCES quest_instances(id), submitted_by_user_id uuid NOT NULL, submitted_at timestamptz NOT NULL, evidence jsonb NOT NULL, checks jsonb NOT NULL, decision text NOT NULL CHECK (decision IN ('VERIFIED','FAILED','PENDING_REVIEW')), reason_code text NOT NULL, reviewer jsonb);
CREATE INDEX quest_attempts_quest_idx ON quest_verification_attempts(quest_id,submitted_at DESC);
CREATE TABLE quest_challenges (id uuid PRIMARY KEY, issuer_user_id uuid NOT NULL, recipient_user_id uuid NOT NULL, party_id uuid NOT NULL, quest_template_id uuid NOT NULL REFERENCES quest_templates(id), quest_id uuid REFERENCES quest_instances(id), title text NOT NULL, description text NOT NULL, category text NOT NULL, explanation text NOT NULL, stake_coins integer NOT NULL CHECK (stake_coins > 0), status text NOT NULL, progress_percent integer NOT NULL DEFAULT 0 CHECK (progress_percent BETWEEN 0 AND 100), last_notice text, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, resolved_at timestamptz, version integer NOT NULL CHECK (version > 0), CHECK (issuer_user_id <> recipient_user_id));
CREATE INDEX quest_challenges_recipient_status_idx ON quest_challenges(recipient_user_id,status,expires_at);
CREATE TABLE quest_want_need_items (id uuid PRIMARY KEY, owner_user_id uuid NOT NULL, kind text NOT NULL CHECK (kind IN ('WANT','NEED')), text text NOT NULL CHECK (char_length(text) BETWEEN 2 AND 160), tags jsonb NOT NULL, converted_quest_id uuid REFERENCES quest_instances(id), created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, version integer NOT NULL CHECK (version > 0));
CREATE INDEX quest_items_owner_idx ON quest_want_need_items(owner_user_id,updated_at DESC);
CREATE TABLE quest_command_results (scope text NOT NULL, idempotency_key text NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(scope,idempotency_key));
CREATE TABLE quest_outbox (id text PRIMARY KEY, event_type text NOT NULL, aggregate_id uuid NOT NULL, envelope jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz);
CREATE INDEX quest_outbox_pending_idx ON quest_outbox(created_at) WHERE published_at IS NULL;
