import type { Clock, EconomyPort, EventPublisher, IdGenerator } from "@sidequest/contracts";
import type { Evidence, QuestInstance, QuestStatus, QuestTemplate, SpawnContext, VerificationAttempt } from "@sidequest/contracts";
import type { Challenge, ChallengeStatus, PartyMembershipPort } from "@sidequest/contracts";
export const DEMO_TEMPLATES: QuestTemplate[] = [
  { id:"cmu-cleanup", title:"Make campus kinder", description:"Collect three pieces of litter around CMU and dispose of them safely.", category:"mutual-aid", tags:["community","outdoors"], risk:"low", moderation:"approved", social:"friends", reward:30, area:"CMU", cooldownHours:24, requirements:[{type:"GPS",target:{latitude:40.4433,longitude:-79.9431},radiusMeters:500,maxAccuracyMeters:100},{type:"TIME",deadline:"2099-12-31T23:59:59.000Z"}] },
  { id:"pgh-reconnect", title:"Send a real check-in", description:"Reconnect with someone you care about with a thoughtful message.", category:"reconnect", tags:["friends","kindness"], risk:"low", moderation:"approved", social:"either", reward:20, area:"PITTSBURGH", cooldownHours:12, requirements:[{type:"PHOTO",prompt:"Show a non-private symbol of your check-in."},{type:"TIME",deadline:"2099-12-31T23:59:59.000Z"}] },
  { id:"cmu-learn", title:"Teach a tiny thing", description:"Teach a friend one useful idea in ten minutes.", category:"learn", tags:["learning","friends"], risk:"low", moderation:"approved", social:"friends", reward:25, area:"CMU", cooldownHours:24, requirements:[{type:"TIME",deadline:"2099-12-31T23:59:59.000Z"}] },
];
const allowed = (s: QuestStatus, next: QuestStatus) => ({SPAWNED:["ACCEPTED","DISMISSED","EXPIRED"],ACCEPTED:["IN_PROGRESS","EXPIRED"],IN_PROGRESS:["VERIFIED","FAILED","EXPIRED"]}[s] ?? []).includes(next);
export class QuestService {
  readonly instances = new Map<string, QuestInstance>(); readonly attempts = new Map<string, VerificationAttempt>(); private readonly done = new Map<string, unknown>();
  constructor(private readonly clock: Clock, private readonly ids: IdGenerator, private readonly economy: EconomyPort, private readonly events: EventPublisher) {}
  spawn(t: QuestTemplate, ownerUserId: string, partyId?: string, expiresInMs = 60*60*1000) { const now=this.clock.now(); const q: QuestInstance={id:this.ids.next(),templateId:t.id,ownerUserId,partyId,participantIds:[ownerUserId],title:t.title,description:t.description,reward:t.reward,requirements:t.requirements,status:"SPAWNED",createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+expiresInMs).toISOString(),version:1}; this.instances.set(q.id,q); return q; }
  transition(id:string,next:QuestStatus,actor:string, key:string) { if(this.done.has(key)) return this.done.get(key) as QuestInstance; const q=this.instances.get(id); if(!q||q.ownerUserId!==actor) throw new Error("NOT_AUTHORIZED"); if(!allowed(q.status,next)) throw new Error("INVALID_TRANSITION"); if(new Date(q.expiresAt)<=this.clock.now()&&next!=="EXPIRED") throw new Error("EXPIRED"); q.status=next; q.version++; if(next==="ACCEPTED") q.acceptedAt=this.clock.now().toISOString(); if(next==="IN_PROGRESS") q.startedAt=this.clock.now().toISOString(); this.done.set(key,q); return q; }
  async submit(id:string, actor:string, evidence:Evidence, key:string) { if(this.done.has(key)) return this.done.get(key); const q=this.instances.get(id); if(!q||q.ownerUserId!==actor) throw new Error("NOT_AUTHORIZED"); if(q.status!=="IN_PROGRESS"&&q.status!=="ACCEPTED") throw new Error("INVALID_TRANSITION"); const checks=q.requirements.map(r=>({type:r.type,passed:r.type==="PHOTO"?!!evidence.photo:r.type==="TIME"?new Date(evidence.submittedAt)<=new Date(r.deadline):!!evidence.gps&&evidence.gps.accuracyMeters<=r.maxAccuracyMeters&&distance(evidence.gps.coordinates,r.target)<=r.radiusMeters,reason:"demo deterministic evaluation"})); const a:VerificationAttempt={id:this.ids.next(),questId:id,evidence,checks,decision:checks.every(c=>c.passed)?"VERIFIED":"FAILED",createdAt:this.clock.now().toISOString()}; this.attempts.set(a.id,a); if(a.decision==="VERIFIED"){q.status="VERIFIED";q.resolvedAt=a.createdAt; await this.economy.apply({operationId:`quest-reward:${id}`,userId:actor,amount:q.reward,reason:"QUEST_REWARD",relatedEntityId:id});} else q.status="FAILED"; q.version++; await this.events.publish({id:this.ids.next(),type:"quest.resolved",version:1,occurredAt:a.createdAt,actorUserId:actor,partyId:q.partyId,aggregateId:id,correlationId:key,payload:{questId:id,status:q.status,reward:q.reward}}); this.done.set(key,a); return a; }
  suggest(ctx:SpawnContext, templates=DEMO_TEMPLATES) { return templates.filter(t=>t.area===ctx.area&&t.moderation==="approved"&&(t.social===ctx.social||t.social==="either")&&t.tags.some(x=>ctx.tags.includes(x))&&!ctx.completedTemplateIds.includes(t.id)&&ctx.activeCount<5).sort((a,b)=>a.id.localeCompare(b.id)).map(t=>({...t,reason:`matches ${t.category} near ${ctx.area}`})); }
}
export class ChallengeService {
  readonly challenges = new Map<string, Challenge>(); private readonly done = new Map<string, unknown>();
  constructor(private readonly clock: Clock, private readonly ids: IdGenerator, private readonly economy: EconomyPort, private readonly membership: PartyMembershipPort) {}
  async issue(issuerUserId:string, recipientUserId:string, partyId:string, questTemplateId:string, stake:number, expiresAt:string, key:string) { if(this.done.has(key)) return this.done.get(key); if(issuerUserId===recipientUserId||stake<1||!Number.isSafeInteger(stake)||!(await this.membership.isMember(issuerUserId,partyId))||!(await this.membership.isMember(recipientUserId,partyId))) throw Error("INVALID_CHALLENGE"); await this.economy.apply({operationId:`challenge-escrow:${key}`,userId:issuerUserId,amount:-stake,reason:"CHALLENGE_ESCROW"}); const c:Challenge={id:this.ids.next(),issuerUserId,recipientUserId,partyId,questTemplateId,stake,status:"PENDING",expiresAt,version:1}; this.challenges.set(c.id,c); this.done.set(key,c); return c; }
  async respond(id:string,userId:string,accept:boolean,key:string) { if(this.done.has(key)) return this.done.get(key); const c=this.challenges.get(id); if(!c||c.recipientUserId!==userId||c.status!=="PENDING") throw Error("INVALID_CHALLENGE"); if(new Date(c.expiresAt)<=this.clock.now()) { c.status="EXPIRED"; throw Error("EXPIRED"); } if(!accept){c.status="DECLINED";await this.economy.apply({operationId:`challenge-refund:${id}`,userId:c.issuerUserId,amount:c.stake,reason:"REFUND",relatedEntityId:id});} else {await this.economy.apply({operationId:`challenge-recipient-escrow:${id}`,userId:userId,amount:-c.stake,reason:"CHALLENGE_ESCROW",relatedEntityId:id});c.status="ACCEPTED";} c.version++;this.done.set(key,c);return c; }
  async outcome(id:string,verified:boolean,key:string){if(this.done.has(key))return this.done.get(key);const c=this.challenges.get(id);if(!c||c.status!=="ACCEPTED")throw Error("INVALID_CHALLENGE");const winner=verified?c.recipientUserId:c.issuerUserId;await this.economy.apply({operationId:`challenge-payout:${id}`,userId:winner,amount:c.stake*2,reason:"CHALLENGE_PAYOUT",relatedEntityId:id});c.status=verified?"COMPLETED":"FAILED";c.version++;this.done.set(key,c);return c;}
}
function distance(a:{latitude:number;longitude:number},b:{latitude:number;longitude:number}) { const p=Math.PI/180; const x=(b.longitude-a.longitude)*p*Math.cos((a.latitude+b.latitude)*p/2); const y=(b.latitude-a.latitude)*p; return Math.sqrt(x*x+y*y)*6371000; }
